### ISSUE TITLE
chain_config is missing

### ISSUE THREAD

**Issue by Netherdrake** [paralink-network/paralink-node#42]
**The documentation says:**
On the first run a default chain config will be created (~/.paralink/chain_config.json). Modify it to include your own set of chains. 

**However the software does not seem to do that:**
```
paralink_node_1  | Loading .env environment variables...
paralink_node_1  | Traceback (most recent call last):
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/bin/alembic", line 8, in <module>
paralink_node_1  |     sys.exit(main())
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 559, in main
paralink_node_1  |     CommandLine(prog=prog).main(argv=argv)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 553, in main
paralink_node_1  |     self.run_cmd(cfg, options)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 530, in run_cmd
paralink_node_1  |     fn(
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
paralink_node_1  |     script.run_env()
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/script/base.py", line 481, in run_env
paralink_node_1  |     util.load_python_file(self.dir, "env.py")
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
paralink_node_1  |     module = load_module_py(module_id, path)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
paralink_node_1  |     spec.loader.exec_module(module)
paralink_node_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
paralink_node_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
paralink_node_1  |   File "src/migrations/env.py", line 10, in <module>
paralink_node_1  |     from src.config import config as app_config  # noqa: E402
paralink_node_1  |   File "./src/__init__.py", line 13, in <module>
paralink_node_1  |     from src.config import config
paralink_node_1  |   File "./src/config.py", line 108, in <module>
paralink_node_1  |     config = Config()
paralink_node_1  |   File "./src/config.py", line 105, in __init__
paralink_node_1  |     json.dump(chains_json, open(chain_config.absolute(), "w"))
paralink_node_1  | PermissionError: [Errno 13] Permission denied: '/home/worker/.paralink/chain_config.json'
paralink_node_1  | Loading .env environment variables...
paralink_node_1  | Traceback (most recent call last):
paralink_node_1  |   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
paralink_node_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
paralink_node_1  |   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
paralink_node_1  |     __import__(pkg_name)
paralink_node_1  |   File "/node/src/__init__.py", line 13, in <module>
paralink_node_1  |     from src.config import config
paralink_node_1  |   File "/node/src/config.py", line 108, in <module>
paralink_node_1  |     config = Config()
paralink_node_1  |   File "/node/src/config.py", line 105, in __init__
paralink_node_1  |     json.dump(chains_json, open(chain_config.absolute(), "w"))
paralink_node_1  | PermissionError: [Errno 13] Permission denied: '/home/worker/.paralink/chain_config.json'

```

**Comment by Netherdrake** [comment]
Closing for now, since this is UX/documentation issue.
